### PR TITLE
Fix vmsh

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by pogoba** [comment]
87ec1e8  how would you determine the ip automatically?
c6582f7  breaks my setup. However in past versions this was necessary.

**Comment by Mic92** [comment]
> [87ec1e8](https://github.com/pogobanane/lambda-pirate/commit/87ec1e866a4cd6a87927c6bc520e7795dc02e38e) how would you determine the ip automatically?

I don't know. I don't know which ip docker wants to see there to be honest. In theory one could just make a dummy interface and assign an address.

> [c6582f7](https://github.com/pogobanane/lambda-pirate/commit/c6582f76c7d0b5d0e67a661c6bc5a2d9937932bf) breaks my setup. However in past versions this was necessary.

I removed this one.

**Comment by pogoba** [comment]
commits required for martha merged in #24. Firecracker seems to be started on martha, function invocation fails.

**Comment by pogoba** [comment]
main is now maintained again. Please rebase PRs on it.

**Pull request closed without merging**
